# Generated by Django 6.0.8 on 2026-09-08 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_sandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='Reference')),
                ('application_type', models.CharField(db_index=True, max_length=100, verbose_name='Application type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('outcome', models.JSONField(blank=True, default=dict, verbose_name='Outcome')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experience_applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_experience_applications', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_applications', through='experiences.ApplicationDependency', through_fields=('application', 'depends_on'), to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFormUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(max_length=100, verbose_name='Form key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_uses', to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='applicationdependency',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links', to='experiences.applicationinstance'),
        ),
        migrations.AddField(
            model_name='applicationdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_links', to='experiences.applicationinstance'),
        ),
        migrations.CreateModel(
            name='ApplicationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(blank=True, max_length=80, verbose_name='Application role')),
                ('direct_permissions', models.JSONField(blank=True, default=list, verbose_name='Additional permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_experience_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_access_grants', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationQueryThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('awaiting_applicant', 'Awaiting applicant'), ('awaiting_reviewer', 'Awaiting reviewer'), ('resolved', 'Resolved')], db_index=True, default='awaiting_applicant', max_length=30)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_threads', to='experiences.applicationinstance')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_application_queries', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_application_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationQueryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('message', 'Message'), ('event', 'Event')], default='message', max_length=20)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_query_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='experiences.applicationquerythread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='Reference')),
                ('form_key', models.CharField(db_index=True, max_length=100, verbose_name='Form key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('reuse_scope', models.CharField(choices=[('organisation', 'Organisation'), ('product', 'Product'), ('application', 'Application only')], db_index=True, default='product', max_length=20, verbose_name='Reuse scope')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experience_form_records', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_form_records', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name', 'created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='applications', through='experiences.ApplicationFormUse', to='experiences.formrecord'),
        ),
        migrations.AddField(
            model_name='applicationformuse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_uses', to='experiences.formrecord'),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(max_length=100, verbose_name='Form key')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('needs_changes', 'Needs changes')], default='completed', max_length=30, verbose_name='Status')),
                ('data', models.JSONField(default=dict, verbose_name='Validated data')),
                ('field_schema', models.JSONField(blank=True, default=list, verbose_name='Field schema')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('submission_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='experiences.formrecord')),
                ('origin_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_form_submissions', to='experiences.applicationinstance')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_number', '-revision', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='experience-attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_attachments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='experiences.formsubmission')),
            ],
            options={
                'ordering': ['field_key', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applicationquerythread',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_threads', to='experiences.formsubmission'),
        ),
        migrations.AddField(
            model_name='applicationformuse',
            name='selected_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_uses', to='experiences.formsubmission'),
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('form_submitted', 'Form submitted'), ('outcome_issued', 'Product outcome issued'), ('action', 'Action'), ('status_changed', 'Status changed'), ('access_changed', 'Access changed'), ('query', 'Query')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_key', models.CharField(blank=True, max_length=100)),
                ('status_before', models.CharField(blank=True, max_length=50)),
                ('status_after', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='experiences.applicationinstance')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='experiences.formsubmission')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('product_type', models.CharField(choices=[('hmis', 'Hospital management information system (HMIS)'), ('lmis', 'Laboratory management information system (LMIS)'), ('emr', 'Electronic medical record (EMR)'), ('phr_locker', 'Personal health record (PHR) application'), ('health_locker', 'Health locker'), ('telemedicine', 'Telemedicine platform'), ('pharmacy', 'Pharmacy system'), ('claims_platform', 'Health claims or insurance platform'), ('health_services_platform', 'Health-service discovery or delivery platform'), ('connector', 'ABDM connector or middleware'), ('other', 'Other digital health solution')], max_length=80, verbose_name='Product type')),
                ('description', models.TextField(verbose_name='Product and intended use')),
                ('website', models.URLField(blank=True, verbose_name='Product website')),
                ('current_facility_count', models.PositiveIntegerField(default=0, verbose_name='Facilities currently using the product')),
                ('deployment_regions', models.TextField(blank=True, verbose_name='Deployment states / union territories')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experience_products', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='formrecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_records', to='experiences.product'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='experiences.product'),
        ),
        migrations.CreateModel(
            name='ProductOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(db_index=True, max_length=100, verbose_name='Outcome type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('data', models.JSONField(default=dict, verbose_name='Structured data')),
                ('field_schema', models.JSONField(blank=True, default=list, verbose_name='Field schema')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_product_outcomes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='experiences.product')),
                ('source_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_outcomes', to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['-issued_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationdependency',
            constraint=models.UniqueConstraint(fields=('application', 'depends_on'), name='unique_application_dependency'),
        ),
        migrations.AddConstraint(
            model_name='applicationdependency',
            constraint=models.CheckConstraint(condition=models.Q(('application', models.F('depends_on')), _negated=True), name='application_cannot_depend_on_itself'),
        ),
        migrations.AddConstraint(
            model_name='applicationaccess',
            constraint=models.UniqueConstraint(fields=('application', 'user'), name='unique_user_access_per_application'),
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(fields=('form', 'submission_number', 'revision'), name='unique_form_submission_revision'),
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('form',), name='unique_current_form_submission'),
        ),
        migrations.AddIndex(
            model_name='formattachment',
            index=models.Index(fields=['submission', 'field_key', 'is_current'], name='exp_current_attachment_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationformuse',
            constraint=models.UniqueConstraint(fields=('application', 'form_key'), name='unique_form_use_per_application'),
        ),
        migrations.AddConstraint(
            model_name='applicationformuse',
            constraint=models.UniqueConstraint(fields=('application', 'form'), name='unique_form_record_per_application'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='unique_product_slug_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='formrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('reuse_scope', 'organisation')), fields=('organisation', 'form_key'), name='unique_organisation_form_record'),
        ),
        migrations.AddConstraint(
            model_name='formrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('reuse_scope', 'product')), fields=('product', 'form_key'), name='unique_product_form_record'),
        ),
        migrations.AddConstraint(
            model_name='formrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('reuse_scope', 'organisation')), models.Q(('product__isnull', False), ('reuse_scope__in', ['product', 'application'])), _connector='OR'), name='form_record_scope_matches_product'),
        ),
        migrations.AddIndex(
            model_name='applicationinstance',
            index=models.Index(fields=['product', 'application_type', 'status'], name='exp_product_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoutcome',
            constraint=models.UniqueConstraint(fields=('product', 'outcome_type', 'source_application'), name='unique_product_outcome_per_application'),
        ),
    ]
