# Generated by Django 6.0.8 on 2026-09-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationaccess',
            name='unique_user_access_per_application',
        ),
        migrations.RemoveField(
            model_name='applicationquerymessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='applicationquerymessage',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='applicationquerythread',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationquerythread',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='applicationquerythread',
            name='opened_by',
        ),
        migrations.RemoveField(
            model_name='applicationquerythread',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='applicationinstance',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_facility_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deployment_regions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='website',
        ),
        migrations.RemoveField(
            model_name='applicationaccess',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationaccess',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='applicationaccess',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicationEvent',
        ),
        migrations.DeleteModel(
            name='ApplicationQueryMessage',
        ),
        migrations.DeleteModel(
            name='ApplicationQueryThread',
        ),
        migrations.DeleteModel(
            name='ApplicationAccess',
        ),
    ]
