# Generated by Django 6.0.8 on 2026-09-08 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError



class AdoptModel(migrations.CreateModel):
    """Move an installed portal table, or create it on a fresh database."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        legacy_table = f"sandbox_{self.name_lower}"
        if legacy_table in schema_editor.connection.introspection.table_names():
            schema_editor.alter_db_table(model, legacy_table, model._meta.db_table)
        else:
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        raise IrreversibleError("Portal model ownership cannot be reversed.")


class AdoptConstraint(migrations.AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        with schema_editor.connection.cursor() as cursor:
            constraints = schema_editor.connection.introspection.get_constraints(
                cursor, model._meta.db_table,
            )
        if self.constraint.name not in constraints:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('events', '0001_initial'),
        ('experiences', '0002_remove_legacy_features'),
        ('organisations', '0004_alter_organisation_verification_status'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AdoptModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
        ),
        AdoptModel(
            name='ProductWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox_id', models.CharField(max_length=32, unique=True)),
                ('solution_type', models.CharField(choices=[('clinical_hmis', 'Clinical HMIS'), ('eua', 'EUA'), ('health_locker', 'Health Locker')], max_length=40)),
                ('applied_milestones', models.JSONField(default=list)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending registration'), ('registered', 'Registered'), ('sent_back', 'Sent back')], default='pending', max_length=24)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='experiences.product')),
            ],
        ),
        AdoptModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('organisation_verification', 'Organisation verification'), ('product_registration', 'Product registration'), ('exit_request', 'Exit request')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'In progress'), ('new', 'New'), ('in_review', 'Under review'), ('query_raised', 'Query raised'), ('approved', 'Approved'), ('sent_back', 'Sent back')], db_index=True, default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resubmission_count', models.PositiveIntegerField(default=0)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_review', to='experiences.applicationinstance')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sandbox_reviews', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_sandbox_reviews', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_reviews', to='experiences.formrecord')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_reviews', to='organisations.organisation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_reviews', to='experiences.product')),
                ('selected_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_reviews', to='experiences.formsubmission')),
            ],
            options={
                'ordering': ['submitted_at', 'pk'],
            },
        ),
        AdoptModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_events', to='organisations.organisation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_events', to='experiences.product')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='experiences.reviewitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        AdoptModel(
            name='ReviewQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='form', max_length=100)),
                ('question', models.TextField()),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries', to='experiences.reviewitem')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_questions', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_replies', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.formsubmission')),
            ],
            options={
                'ordering': ['raised_at', 'pk'],
            },
        ),
        AdoptModel(
            name='SandboxCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('encrypted_secret', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('gateway_url', models.URLField()),
                ('callback_url', models.URLField(blank=True)),
                ('bridge_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rotation_due', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_credential', to='experiences.product')),
            ],
        ),
        AdoptModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sandbox-support/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage')),
            ],
        ),
        AdoptModel(
            name='TicketContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(blank=True, choices=[('', 'General'), ('HI-CM', 'HI-CM'), ('UHI', 'UHI'), ('NHCX', 'NHCX'), ('PHR', 'PHR'), ('HealthLocker', 'HealthLocker')], max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.product')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_context', to='support.ticket')),
            ],
        ),
        AdoptModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='sandbox_unique_event_registration')],
            },
        ),
        AdoptModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('m1', 'M1: ABHA and identity'), ('m2', 'M2: HIP services'), ('m3', 'M3: HIU services'), ('m4', 'M4: HFR Registration'), ('phr1', 'PHR1: PHR application flows'), ('locker1', 'PHR1: Locker flows'), ('uhi1', 'UHI1: UHI participant flows')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='milestone', to='experiences.applicationinstance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='experiences.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'key'), name='sandbox_unique_product_milestone')],
            },
        ),
        AdoptConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'organisation_verification')), fields=('organisation',), name='sandbox_one_org_review'),
        ),
        AdoptConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'product_registration')), fields=('product',), name='sandbox_one_product_review'),
        ),
        AdoptConstraint(
            model_name='reviewitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('kind', 'organisation_verification'), ('product__isnull', True)), models.Q(('application__isnull', False), ('kind__in', ['product_registration', 'exit_request']), ('product__isnull', False)), _connector='OR'), name='sandbox_review_subject_required'),
        ),
    ]
