# Generated by Django 6.0.8 on 2026-09-08 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generalize_review_kind(apps, schema_editor):
    apps.get_model("experiences", "ReviewItem").objects.filter(
        kind="exit_request",
    ).update(kind="application")


def restore_review_kind(apps, schema_editor):
    apps.get_model("experiences", "ReviewItem").objects.filter(
        kind="application",
    ).update(kind="exit_request")


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0001_initial'),
        ('experiences', '0004_generalize_portal_records'),
        ('organisations', '0005_remove_legacy_features'),
        ('support', '0002_remove_legacy_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='sandbox_unique_event_registration',
        ),
        migrations.RemoveConstraint(
            model_name='milestone',
            name='sandbox_unique_product_milestone',
        ),
        migrations.RemoveConstraint(
            model_name='reviewitem',
            name='sandbox_one_org_review',
        ),
        migrations.RemoveConstraint(
            model_name='reviewitem',
            name='sandbox_one_product_review',
        ),
        migrations.RemoveConstraint(
            model_name='reviewitem',
            name='sandbox_review_subject_required',
        ),
        migrations.RunPython(generalize_review_kind, restore_review_kind),
        migrations.AlterField(
            model_name='auditevent',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='experiences.product'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=80, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productcredential',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credential', to='experiences.product'),
        ),
        migrations.AlterField(
            model_name='productworkspace',
            name='solution_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_item', to='experiences.applicationinstance'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_review_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_review_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='experiences.formrecord'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='kind',
            field=models.CharField(choices=[('organisation_verification', 'Organisation verification'), ('product_registration', 'Product registration'), ('application', 'Application request')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='experiences.product'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='selected_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='experiences.formsubmission'),
        ),
        migrations.AlterField(
            model_name='reviewquery',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewquery',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='experience-support/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='ticketcontext',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_context', to='support.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketcontext',
            name='track',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='experience_unique_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('product', 'key'), name='experience_unique_product_milestone'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'organisation_verification')), fields=('organisation',), name='experience_one_org_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'product_registration')), fields=('product',), name='experience_one_product_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('kind', 'organisation_verification'), ('product__isnull', True)), models.Q(('application__isnull', False), ('kind__in', ['product_registration', 'application']), ('product__isnull', False)), _connector='OR'), name='review_item_subject_required'),
        ),
    ]
