# Generated by Django 6.0.8 on 2026-09-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0005_generalize_workflow_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=100)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("review", "Reviews"),
                            ("support", "Support"),
                            ("events", "Events"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="General/onboarding, a program category, or all categories.",
                        max_length=100,
                    ),
                ),
                ("can_read", models.BooleanField(default=True)),
                ("can_write", models.BooleanField(default=False)),
                ("can_approve", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "program", "area", "category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "program", "area", "category"),
                        name="unique_experience_access_grant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("can_read", True),
                            models.Q(("can_approve", False), ("can_write", False)),
                            _connector="OR",
                        ),
                        name="experience_write_approve_requires_read",
                    ),
                ],
            },
        ),
    ]
