# Generated by Django 6.0.8 on 2026-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0006_accessgrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate an agency to remove it from new selections.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "certification agencies",
                "ordering": ["sort_order", "name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "name"),
                        name="unique_certification_agency_per_program",
                    )
                ],
            },
        ),
    ]
