"""Seed the legacy WASA options once; administrators manage subsequent changes.

Source: supplied ABDM.zip, frontend src/constants/security-audit-agencies.js.
Option order and exact strings are retained for existing submission compatibility.
"""

from django.db import migrations


LEGACY_WASA_AGENCIES = (
    "Army Cyber Group",
    "Centre for Development of Advanced Computing (C-DAC)",
    "Kerala State Electronics Development Corporation Ltd.",
    "Kerala University of Digital Sciences, Innovation and Technology",
    "M/s 9USRcraft",
    "M/s A3S Tech & Company",
    "M/s AAA Technologies Ltd",
    "M/s AKS Information Technology Services Pvt Ltd",
    "M/s ANA Cyber Forensic Private Limited",
    "M/s ANB Solutions Private Limited",
    "M/s ANZEN Technologies Pvt. Ltd.",
    "M/s AQM Technologies Pvt Ltd",
    "M/s ARM Innovations Private Limited",
    "M/s ASA & Associates LLP",
    "M/s ASPL Info Services Private Limited",
    "M/s AURISEG Consulting Private Limited",
    "M/s AVASURE Technologies Pvt. Ltd.",
    "M/s Accedere Limited",
    "M/s Accenture Solutions Pvt. Ltd.",
    "M/s Acquisory Consulting LLP",
    "M/s Allied Boston Consultants India Pvt. Ltd.",
    "M/s Alten Calsoft Labs (India) Private Limited",
    "M/s Ameya Cyber Risk Solutions Pvt. Ltd.",
    "M/s Amigosec Consulting Private Limited (SynRadar)",
    "M/s Andhra Pradesh Technology Services Ltd",
    "M/s Ankura Consulting India Private Limited",
    "M/s Arridae Infosec Private Limited",
    "M/s Associated IT Consultants Private Limited",
    "M/s Astra Security (Czar Securities Pvt. Ltd.)",
    "M/s Audix Techno Consulting Solutions Private Limited",
    "M/s Aujas Cybersecurity Limited",
    "M/s Aurionpro Solutions Limited",
    "M/s AuthenticOne Cybersecurity Private Limited",
    "M/s BDO India LLP",
    "M/s BSCIC Certifications Private Limited ",
    "M/s BSE Technologies Private Limited",
    "M/s Be4Breach",
    "M/s Beagle Cyber Innovations Private Limited",
    "M/s Bharat Electronics Limited",
    "M/s BharatCyber Solutions LLP",
    "M/s Bharti Airtel Service Limited",
    "M/s Black Box Limited",
    "M/s Bosch Global Software Technologies Pvt. Ltd.",
    "M/s Briskinfosec Technology and Consulting Pvt. Ltd.",
    "M/s Bug Hunters Private Limited",
    "M/s CEREIV Advisory LLP",
    "M/s CMS IT Services Pvt. Ltd. ",
    "M/s Certbar Security Private Limited",
    "M/s Certcube Labs Pvt. Ltd.",
    "M/s Climate ETC Technology Services Private Limited",
    "M/s Cloud4C Services Private Limited",
    "M/s Code Decode Labs",
    "M/s Codec Networks Pvt. Ltd.",
    "M/s ConsultEdge Global Services (OPC) Private Limited",
    "M/s ControlCase International Pvt. Ltd.",
    "M/s CoreIT Services Pvt. Ltd.",
    "M/s Crossbow Labs LLP",
    "M/s Crowe Advisory Services (India) LLP",
    "M/s CuttingEdge Solutions India Private Limited",
    "M/s CyRAAC Services Private Limited",
    "M/s Cyber Security Works Pvt. Ltd.",
    "M/s CyberCube Services Pvt. Ltd.",
    "M/s CyberNX Technologies Pvt. Ltd.",
    "M/s CyberSRC Consultancy Private Limited",
    "M/s CyberXchange Private Limited",
    "M/s Cybernerds Solutions Private Limited",
    "M/s Cybersigma Consulting Services LLP",
    "M/s Cybersmith Secure Private Limited",
    "M/s Cybertryzub Infosec Pvt. Ltd.",
    "M/s Cyethack Solutions Private Limited",
    "M/s Cynox Security LLP",
    "M/s Cypros Technologies Private Limited",
    "M/s DarkNext LLP",
    "M/s Deccan Infotech (P) Ltd.",
    "M/s Defhawk TechServices Private Limited",
    "M/s Deloitte Touche Tohmatsu India LLP",
    "M/s DigiFortex Technologies Private Limited",
    "M/s Digital Age Strategies Pvt. Ltd.",
    "M/s DigitalTrack Solutions Pvt. Ltd.",
    "M/s Dr CBS Cyber Security Services LLP",
    "M/s Dreamworks Infotech Private Limited",
    "M/s ESF Labs Limited",
    "M/s Entersoft Information Systems Private Limited",
    "M/s Ernst & Young LLP",
    "M/s Evanti Tech Private Limited",
    "M/s Eventus Security Private Limited",
    "M/s Eventus TechSol Private Limited",
    "M/s Expleo Solutions Limited",
    "M/s Five Tattva Cyberhub Security LLP",
    "M/s Forensic CyberTech Private Limited",
    "M/s Fortune4 Expert Advisors",
    "M/s G-Info Technology Solutions Pvt. Ltd.",
    "M/s G. D. Apte & Company",
    "M/s GRM Technologies Private Limited",
    "M/s GlobalTech & Infosec Pvt. Ltd.",
    "M/s Globals ITES Private Limited",
    "M/s Grant Thornton Bharat LLP",
    "M/s HKIT Security Solutions",
    "M/s HackIT Technology and Advisory Services",
    "M/s HackersFood Private Limited",
    "M/s Happiest Minds Technologies Limited",
    "M/s HiTrust Infotech Solutions Private Limited",
    "M/s Hitachi Systems India Private Limited",
    "M/s Honeywell Automation India Limited",
    "M/s IBM India Pvt. Ltd.",
    "M/s IEMA Research & Development Pvt. Ltd.",
    "M/s IHUB NTIHAC Foundation (C3iHub)",
    "M/s IITM Pravartak Technologies Foundation",
    "M/s ISECURION Technology & Consulting Pvt. Ltd.",
    "M/s ISOAH Data Securities Private Limited",
    "M/s Imperium Solutions",
    "M/s Indusface Pvt. Ltd.",
    "M/s Infocus IT Consulting Private Limited",
    "M/s Infopercept Consulting Private Limited",
    "M/s InnSpark Solutions Private Limited",
    "M/s Innovador Infotech Private Limited",
    "M/s Innowave IT Infrastructures Limited",
    "M/s Inspira Enterprise India Ltd",
    "M/s Intelliroot Technologies (OPC) Private Limited",
    "M/s InventOnUs Tech Pvt. Ltd.",
    "M/s Itorizin Technology Solutions Pvt. Ltd.",
    "M/s JHS & Associates LLP",
    "M/s Jio Platforms Limited",
    "M/s John and Smith Solutions LLP",
    "M/s K7 Enterprise Security Private Limited",
    "M/s KCyber Experts Pvt. Ltd.",
    "M/s KPMG Assurance and Consulting Services LLP",
    "M/s Kalkin Intelligence Private Limited",
    "M/s Kirtane & Pandit LLP",
    "M/s Kochar Consultants Private Limited",
    "M/s Kratikal Tech Private Limited",
    "M/s Levithan Technologies Private Limited",
    "M/s Lorcam Solutions Private Limited",
    "M/s Macksofy Technologies Pvt. Ltd.",
    "M/s Mahindra Special Services Group",
    "M/s MapleCloud Technologies",
    "M/s Marven Data Systems Private Limited",
    "M/s Matrix3D Infocom Pvt. Ltd.",
    "M/s Maverick Quality Advisory Services Private Limited",
    "M/s Mazars Business Advisors Private Limited",
    "M/s Mindsprint Digital (India) Private Limited",
    "M/s Mirox Cyber Security & Technology Pvt. Ltd.",
    "M/s Mitkat Advisory Services Private Limited",
    "M/s NG TechAssurance Private Limited",
    "M/s NTT India Private Limited",
    "M/s Nangia & Co LLP",
    "M/s Net Access India Limited",
    "M/s Net Square Solutions Private Limited",
    "M/s Netrika Consulting India Pvt. Ltd.",
    "M/s Netsentries Infosec Solutions Private Limited",
    "M/s Network Intelligence Pvt. Ltd.",
    "M/s OwnZap Infosec Pvt. Ltd.",
    "M/s PKF Consulting Services LLP",
    "M/s PSY9 Security Consulting Private Limited",
    "M/s Paladion Networks Pvt. Ltd.",
    "M/s Panacea InfoSec Pvt. Ltd.",
    "M/s Paralok Information Security Private Limited",
    "M/s Payatu Security Consulting Private Limited",
    "M/s Peneto Labs Pvt. Ltd.",
    "M/s Persistent Systems Ltd",
    "M/s Phoenix TechnoCyber",
    "M/s Precise Testing Solution Pvt. Ltd.",
    "M/s PricewaterhouseCoopers Pvt. Ltd.",
    "M/s Primefort Private Limited",
    "M/s Pristine InfoSolutions Pvt. Ltd.",
    "M/s ProTechmanize Solutions Pvt. Ltd.",
    "M/s Protiviti India Member Private Limited",
    "M/s Pyramid Cyber Security & Forensic Pvt. Ltd.",
    "M/s QOS Technology Private Limited",
    "M/s QRC Assurance and Solutions Private Limited",
    "M/s Qadit Systems and Solutions Pvt. Ltd.",
    "M/s Qseap Infotech Pvt. Ltd.",
    "M/s RAH Infotech Private Limited",
    "M/s RNR Consulting Private Limited",
    "M/s RSM Astute Consulting Pvt. Ltd.",
    "M/s RedHunt Labs India Private Limited",
    "M/s Renault Nissan Technology & Business Centre India",
    "M/s Reserve Bank Information Technology Pvt. Ltd. (ReBIT)",
    "M/s Reverse Engineering Infosec Pvt. Ltd.",
    "M/s Risk Quotient Consultancy Private Limited",
    "M/s RiskBerg Consulting Pvt. Ltd.",
    "M/s Rootnik Labs Cybersecurity Private Limited",
    "M/s SISA Information Security Private Limited",
    "M/s SOC Analyst Private Limited",
    "M/s SQ1 Security Technology Private Limited",
    "M/s Saint Fox Consultancy Private Limited",
    "M/s Saptang Labs Private Limited",
    "M/s Schneider Electric Systems India Pvt. Ltd.",
    "M/s SecLance Private Limited",
    "M/s Secnic Consultancy Services Pvt. Ltd.",
    "M/s Secnuo Consulting (OPC) Private Limited",
    "M/s Sectrio-Subex Digital LLP",
    "M/s Secunatix Consultants Private Limited",
    "M/s SecurEyes Techno Services Pvt. Ltd.",
    "M/s Secure Loopholes Solutions LLP",
    "M/s SecureInteli Technologies Private Limited",
    "M/s SecureNexGen LLP",
    "M/s Security Brigade InfoSec Pvt. Ltd.",
    "M/s Security Innovation India",
    "M/s SecurityBoat Cybersecurity Solutions Pvt. Ltd.",
    "M/s Securityium (OPC) Pvt. Ltd.",
    "M/s Securium Solutions Private Limited",
    "M/s Sequretek IT Solutions Pvt. Ltd.",
    "M/s Shieldbyte Infosec Private Limited",
    "M/s Sicherten Info Consulting Private Limited",
    "M/s Siemens Limited",
    "M/s Sify Digital Services Ltd.",
    "M/s Softcell Technologies Global Pvt. Ltd.",
    "M/s Staqo World Private Limited",
    "M/s Suma Soft Private Limited",
    "M/s Sumeru Technology Solutions Pvt. Ltd.",
    "M/s Sveltetech Technologies Private Limited",
    "M/s Swadesh System Pvt. Ltd.",
    "M/s Synclature Consultancy Private Limited",
    "M/s Synopsys Software Integrity Solutions (India) Pvt. Ltd.",
    "M/s Sysman Computers",
    "M/s TAC InfoSec Limited ",
    "M/s TCG Digital Solutions Pvt. Ltd.",
    "M/s Talakunchi Networks Pvt. Ltd.",
    "M/s Tata Advanced Systems Ltd.",
    "M/s Tata Communications Ltd",
    "M/s Tata Power Delhi Distribution Ltd.",
    "M/s Tech Mahindra Ltd.",
    "M/s TechD Cyber Security Limited",
    "M/s Techdefence Labs Solutions Private Limited",
    "M/s Techensglobal Private Limited",
    "M/s Techumen Infosec Private Limited",
    "M/s Tek Cube Pvt. Ltd. (WeSecureApp)",
    "M/s Terasoft Technologies Pvt. Ltd.",
    "M/s The Intect (Hion Security Pvt. Ltd.)",
    "M/s Third I Information Security Pvt Ltd.",
    "M/s Tribastion Technologies Pvt. Ltd.",
    "M/s Trinay Cyber Technologies Pvt. Ltd.",
    "M/s Tsaaro Solutions Private Limited",
    "M/s Tuxcentrix Consultancy Pvt. Ltd.",
    "M/s TÜV-SÜD South Asia Pvt. Ltd.",
    "M/s US Technology International Private Limited",
    "M/s Utthunga Technologies Pvt. Ltd.",
    "M/s Vault Infosec",
    "M/s Virtual Caim Private Limited",
    "M/s Vista InfoSec",
    "M/s WST Technologies Private Limited",
    "M/s Wings2i IT Solutions Private Limited",
    "M/s Wipro Limited",
    "M/s Xiarch Solutions Private Limited",
    "M/s Yoganandh & Ram LLP",
    "M/s cyberSecurist Technologies Pvt. Ltd.",
    "M/s eSec Forte Technologies Pvt. Ltd.",
    "M/s eSecurify Technologies LLP",
    "M/s iSec Services Pvt. Ltd.",
    "M/s x-Biz Techventures Private Limited",
    "Madhya Pradesh State Electronics Development Corporation",
    "Software Technology Parks of India",
    "Tata Consultancy Services Limited",
    "West Bengal Electronics Industry Development Corporation Ltd. (WEBEL)",
)


def seed_agencies(apps, schema_editor):
    agency = apps.get_model("experiences", "CertificationAgency")
    agency.objects.using(schema_editor.connection.alias).bulk_create(
        [
            agency(program="abdm", name=name, sort_order=order)
            for order, name in enumerate(LEGACY_WASA_AGENCIES)
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [("experiences", "0007_certificationagency")]

    operations = [
        migrations.RunPython(seed_agencies, reverse_code=migrations.RunPython.noop),
    ]
