# Generated by Django 6.0.8 on 2026-09-09 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0007_solution_type_set"),
        ("experiences", "0008_seed_wasa_certification_agencies"),
    ]

    operations = []
