# Generated by Django 6.0.8 on 2026-09-09 18:58

import django.utils.timezone
import uuid
from django.db import migrations, models


def assign_request_ids(apps, schema_editor):
    notification = apps.get_model("experiences", "Notification")
    manager = notification.objects.using(schema_editor.connection.alias)
    for pk in manager.values_list("pk", flat=True).iterator():
        manager.filter(pk=pk).update(request_id=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0009_merge_agency_and_solution_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="cc",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.CharField(
                choices=[("info", "Information"), ("otp", "OTP")],
                default="info",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="from_email",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="notification",
            name="next_attempt_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="notification",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="request_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="template_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(assign_request_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notification",
            name="request_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(
                    ("failed_at__isnull", True), ("sent_at__isnull", True)
                ),
                fields=["next_attempt_at"],
                name="notification_pending_due",
            ),
        ),
    ]
