# Generated by Django 6.0.8 on 2026-09-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0016_retire_product_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productworkspace',
            name='registration_status',
        ),
    ]
