# Generated by Django 6.0.8 on 2026-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0019_m4_has_no_prerequisite'),
    ]

    operations = [
        # Reversing adds the column back to existing products, so it needs a default.
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=80, verbose_name='Product type'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
