# Generated by Django 6.0.8 on 2026-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0022_product_production_issued_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
