# Generated by Django 6.0.8 on 2026-10-02 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0037_fold_product_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='accessgrant',
            name='experience_write_approve_requires_read',
            constraint=models.CheckConstraint(condition=models.Q(('can_read', True), models.Q(('can_approve', False), ('can_write', False)), _connector='OR'), name='experience_write_approve_requires_read', violation_error_message='Write and approve permissions require read access.'),
        ),
        migrations.AlterConstraint(
            model_name='applicationdependency',
            name='application_cannot_depend_on_itself',
            constraint=models.CheckConstraint(condition=models.Q(('application', models.F('depends_on')), _negated=True), name='application_cannot_depend_on_itself', violation_error_message='An application cannot depend on itself.'),
        ),
    ]
