# Generated by Django 6.0.8 on 2026-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0041_rename_abdm_track_to_hiecm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='area',
            field=models.CharField(choices=[('review', 'Reviews'), ('support', 'Support'), ('events', 'Sessions and Activities')], max_length=20),
        ),
    ]
