services:
  docs:
    image: ohc_experience_local_docs
    container_name: ohc_experience_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ohc_experience:/app/ohc_experience:z
    ports:
      - '9000:9000'
    command: /start-docs
