# Generated by Django 6.0.8 on 2026-09-08 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0004_abdm_organisation_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('object_pk', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=60)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox_id', models.CharField(max_length=20, unique=True, verbose_name='Sandbox id')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('hmis', 'HMIS'), ('lmis', 'LMIS'), ('phr_app', 'PHR application'), ('health_locker', 'Health locker'), ('payer_tpa', 'Payer or TPA system'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('solution_type', models.CharField(choices=[('clinical_hmis', 'Clinical HMIS'), ('eua', 'EUA'), ('health_locker', 'Health Locker')], max_length=20, verbose_name='Solution type applying for')),
                ('applied_tracks', models.JSONField(blank=True, default=list, verbose_name='Applied tracks')),
                ('applied_milestones', models.JSONField(blank=True, default=list, verbose_name='Applied milestones')),
                ('registration_status', models.CharField(choices=[('pending', 'Registration pending'), ('registered', 'Registered'), ('sent_back', 'Sent back')], default='pending', max_length=20, verbose_name='Registration status')),
                ('registered_on', models.DateField(blank=True, null=True, verbose_name='Registered on')),
                ('sent_back_reason', models.TextField(blank=True, verbose_name='Send-back reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organisations.organisation', verbose_name='Organisation')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=80, unique=True, verbose_name='Client id')),
                ('secret_encrypted', models.TextField(verbose_name='Client secret')),
                ('gateway_base_url', models.URLField(verbose_name='Gateway base URL')),
                ('callback_url', models.URLField(blank=True, verbose_name='Callback URL')),
                ('bridge_url', models.URLField(blank=True, verbose_name='Bridge URL')),
                ('issued_on', models.DateTimeField(verbose_name='Issued on')),
                ('rotation_due', models.DateField(verbose_name='Rotation due')),
                ('rotated_on', models.DateTimeField(blank=True, null=True, verbose_name='Last rotated')),
                ('revoked_on', models.DateTimeField(blank=True, null=True, verbose_name='Revoked on')),
                ('callback_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('callback_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('callback_checked_at', models.DateTimeField(blank=True, null=True)),
                ('callback_error', models.CharField(blank=True, max_length=255)),
                ('callback_failure_streak', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='abdm.product')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(max_length=20, verbose_name='Track')),
                ('milestone_code', models.CharField(max_length=20, verbose_name='Milestone')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('open', 'Open'), ('in_progress', 'In progress'), ('under_review', 'Under review'), ('query_raised', 'Query raised'), ('approved', 'Approved')], db_index=True, default='locked', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Sandbox testing start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Sandbox testing end')),
                ('demo_date', models.DateField(blank=True, null=True, verbose_name='Tentative demo date')),
                ('wasa_agency', models.CharField(blank=True, max_length=255, verbose_name='WASA audit agency')),
                ('wasa_date', models.DateField(blank=True, null=True, verbose_name='WASA date')),
                ('functional_certificate', models.FileField(blank=True, upload_to='abdm/compliance/%Y/%m/', verbose_name='Functional testing certificate')),
                ('functional_report', models.FileField(blank=True, upload_to='abdm/compliance/%Y/%m/', verbose_name='Functional testing report')),
                ('submitted_on', models.DateTimeField(blank=True, null=True, verbose_name='Submitted on')),
                ('resubmission_count', models.PositiveSmallIntegerField(default=0)),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='Approved on')),
                ('decision_note', models.TextField(blank=True, verbose_name='Decision note')),
                ('sent_back_on', models.DateTimeField(blank=True, null=True, verbose_name='Sent back on')),
                ('sent_back_reason', models.TextField(blank=True, verbose_name='Send-back reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_compliance_records', to=settings.AUTH_USER_MODEL)),
                ('sent_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_back_compliance_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='abdm.product')),
            ],
            options={
                'verbose_name': 'Compliance record',
                'verbose_name_plural': 'Compliance records',
                'ordering': ['product', 'track_code', 'milestone_code'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Reference')),
                ('item_type', models.CharField(choices=[('exit_request', 'Exit request'), ('organisation_verification', 'Organisation verification'), ('product_registration', 'Product registration')], db_index=True, max_length=40, verbose_name='Type')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('query_raised', 'Query raised'), ('approved', 'Approved'), ('sent_back', 'Sent back'), ('withdrawn', 'Withdrawn')], db_index=True, default='new', max_length=20, verbose_name='Status')),
                ('submitted_on', models.DateTimeField(verbose_name='Submitted on')),
                ('resubmission_count', models.PositiveSmallIntegerField(default=0)),
                ('decided_on', models.DateField(blank=True, null=True, verbose_name='Decided on')),
                ('decision_note', models.TextField(blank=True, verbose_name='Decision note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'is_ohc_team': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_items', to=settings.AUTH_USER_MODEL)),
                ('compliance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='abdm.compliancerecord')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_review_items', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='organisations.organisation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='abdm.product')),
            ],
            options={
                'verbose_name': 'Review item',
                'verbose_name_plural': 'Review items',
                'ordering': ['submitted_on', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('started', 'Review started'), ('assigned', 'Assigned'), ('query_raised', 'Query raised'), ('query_answered', 'Query answered'), ('query_resolved', 'Query resolved'), ('approved', 'Approved'), ('sent_back', 'Sent back'), ('withdrawn', 'Withdrawn'), ('milestones_changed', 'Milestones changed'), ('note', 'Note')], max_length=30, verbose_name='Kind')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_history_entries', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='abdm.reviewitem')),
            ],
            options={
                'verbose_name': 'Review history entry',
                'verbose_name_plural': 'Review history entries',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='form', max_length=80, verbose_name='Field')),
                ('field_label', models.CharField(blank=True, max_length=255, verbose_name='Field label')),
                ('question', models.TextField(verbose_name='Question')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('reply', models.TextField(blank=True, verbose_name='Reply')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='abdm.reviewitem')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_review_queries', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_review_queries', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review query',
                'verbose_name_plural': 'Review queries',
                'ordering': ['raised_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='compliancerecord',
            constraint=models.UniqueConstraint(fields=('product', 'track_code', 'milestone_code'), name='unique_compliance_record_per_milestone'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'organisation_verification')), fields=('organisation',), name='unique_organisation_verification_item'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'product_registration')), fields=('product',), name='unique_product_registration_item'),
        ),
    ]
