# Generated by Django 6.0.8 on 2026-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hmis', 'HMIS'), ('lmis', 'LMIS'), ('phr_app', 'PHR application'), ('health_locker', 'Health locker'), ('payer_tpa', 'Payer or TPA system'), ('other', 'Other')], default='hmis', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='solution_type',
            field=models.CharField(choices=[('clinical_hmis', 'Clinical HMIS'), ('eua', 'EUA'), ('health_locker', 'Health Locker')], default='clinical_hmis', max_length=20, verbose_name='Solution type applying for'),
        ),
    ]
