# Generated by Django 6.0.8 on 2026-09-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0003_alter_event_created_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_and__publish_78801a_idx',
            old_name='events_even_publish_26dca1_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('event', 'Event'), ('webinar', 'Webinar'), ('workshop', 'Workshop')], default='event', max_length=20, verbose_name='Kind'),
        ),
    ]
