# Generated by Django 6.0.8 on 2026-10-02 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0004_rename_events_even_publish_26dca1_idx_events_and__publish_78801a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='event',
            name='event_ends_after_it_starts',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='event_ends_after_it_starts', violation_error_message='The event must end after it starts.'),
        ),
    ]
