# Generated by Django 6.0.8 on 2026-10-08 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0005_constraint_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts_at'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Leave blank for an online session.', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterConstraint(
            model_name='event',
            name='event_ends_after_it_starts',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='event_ends_after_it_starts', violation_error_message='The session must end after it starts.'),
        ),
    ]
