# Generated by Django 6.0.8 on 2026-09-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='linked_facility',
        ),
    ]
