# Generated by Django 6.0.8 on 2026-09-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='abdm.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='track',
            field=models.CharField(blank=True, choices=[('HI-CM', 'HI-CM'), ('UHI', 'UHI'), ('NHCX', 'NHCX'), ('PHR', 'PHR'), ('HealthLocker', 'HealthLocker')], max_length=20, verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='support/attachments/%Y/%m/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('sandbox', 'Sandbox and credentials'), ('api', 'Gateway APIs'), ('certification', 'Milestones and exit'), ('deployment', 'Production onboarding'), ('billing', 'Account and organisation')], default='sandbox', max_length=20, verbose_name='Category'),
        ),
    ]
