# Generated by Django 6.0.8 on 2026-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_ticket_phr_app_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='kind',
            field=models.CharField(choices=[('reply', 'Reply'), ('event', 'Status change'), ('priority', 'Priority change')], default='reply', max_length=10),
        ),
    ]
