# Generated by Django 6.0.8 on 2026-09-09 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0006_accessgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation id')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_runs', to='experiences.product', verbose_name='Product')),
                ('started_by', models.ForeignKey(blank=True, help_text='Null when registration started it rather than a person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_runs_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provisioning run',
                'verbose_name_plural': 'Provisioning runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('KEYCLOAK', 'Keycloak'), ('WSO2', 'WSO2'), ('HIECM', 'HIE-CM')], max_length=20)),
                ('external_ref', models.CharField(max_length=255)),
                ('public_ref', models.CharField(blank=True, max_length=255)),
                ('secret_ref', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('FAILED', 'Failed'), ('ORPHANED', 'Orphaned')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioned_resources', to='experiences.product')),
            ],
            options={
                'indexes': [models.Index(fields=['system', 'state'], name='integrations_system_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'system'), name='integrations_provisioned_resource_unique_product_system'), models.CheckConstraint(condition=models.Q(('system__in', ['KEYCLOAK', 'WSO2', 'HIECM'])), name='integrations_provisioned_resource_system_valid'), models.CheckConstraint(condition=models.Q(('state__in', ['ACTIVE', 'DISABLED', 'FAILED', 'ORPHANED'])), name='integrations_provisioned_resource_state_valid')],
            },
        ),
    ]
