# Generated by Django 6.0.8 on 2026-09-08 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sent_back_replaces_rejected(apps, schema_editor):
    Organisation = apps.get_model("organisations", "Organisation")
    Organisation.objects.filter(verification_status="rejected").update(
        verification_status="sent_back",
    )


def rejected_replaces_sent_back(apps, schema_editor):
    Organisation = apps.get_model("organisations", "Organisation")
    Organisation.objects.filter(verification_status="sent_back").update(
        verification_status="rejected",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_sandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.CharField(blank=True, choices=[('india_entity', 'Entity in India'), ('foreign_with_indian_subsidiary', 'Foreign entity with an Indian subsidiary'), ('academic', 'Academic or research institution')], max_length=40, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='district',
            field=models.CharField(blank=True, max_length=120, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('private_company', 'Private company'), ('government_body', 'Government body'), ('sole_proprietorship', 'Sole proprietorship'), ('trust_or_society', 'Trust or society'), ('section_8', 'Section 8 company'), ('llp', 'Limited liability partnership')], max_length=30, verbose_name='Type of entity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='organisations/logos/%Y/%m/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='registered_address',
            field=models.TextField(blank=True, verbose_name='Registered address'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='organisations/verification/%Y/%m/', verbose_name='Supporting document'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_document_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Verification document number'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_document_type',
            field=models.CharField(blank=True, choices=[('PAN', 'PAN'), ('GSTIN', 'GSTIN'), ('CIN', 'CIN')], max_length=10, verbose_name='Verification document type'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_reason',
            field=models.TextField(blank=True, help_text='Shown to the integrator when verification is sent back.', verbose_name='Send-back reason'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted for verification at'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organisations', to=settings.AUTH_USER_MODEL, verbose_name='Verified by'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the entity'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Verification pending'), ('verified', 'Verified'), ('sent_back', 'Sent back')], default='pending', max_length=20, verbose_name='Verification status'),
        ),
        migrations.RunPython(
            sent_back_replaces_rejected,
            rejected_replaces_sent_back,
        ),
    ]
