# Generated by Django 6.0.8 on 2026-09-08 12:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0003_sandbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Verification pending"),
                    ("verified", "Verified vendor"),
                    ("rejected", "Verification rejected"),
                    ("sent_back", "Sent back"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Verification status",
            ),
        ),
    ]
