# Generated by Django 6.0.8 on 2026-09-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_organisation_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='deployment_regions',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='technical_contact_email',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='technical_contact_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='technical_contact_phone',
        ),
        migrations.DeleteModel(
            name='Sandbox',
        ),
    ]
