# Generated by Django 6.0.8 on 2026-09-08 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='materials_url',
            field=models.URLField(blank=True, verbose_name='Slides or materials link'),
        ),
        migrations.AddField(
            model_name='event',
            name='recording_url',
            field=models.URLField(blank=True, verbose_name='Recording link'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event registration',
                'verbose_name_plural': 'Event registrations',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_registration_per_event')],
            },
        ),
    ]
