# Generated by Django 6.0.8 on 2026-09-09 12:21

import ohc_experience.experiences.registry
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="program",
            field=models.CharField(
                default=ohc_experience.experiences.registry.default_program_key,
                max_length=100,
            ),
        ),
    ]
